### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'has_key' in honeybadger.notify()

### ISSUE THREAD

**Issue by vineesha** [honeybadger-io/honeybadger-python#17]
Facing this when using HoneyBadger with Python 3.5:

```
Traceback (most recent call last):
  File "/Users/vineesha/Paysense/arthamatics/venv1/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/vineesha/Paysense/arthamatics/venv1/lib/python3.5/site-packages/django/core/handlers/base.py", line 262, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/Users/vineesha/Paysense/arthamatics/venv1/lib/python3.5/site-packages/honeybadger/middleware.py", line 18, in process_exception
    honeybadger.notify(exception)
  File "/Users/vineesha/Paysense/arthamatics/venv1/lib/python3.5/site-packages/honeybadger/core.py", line 46, in notify
    self._send_notice(exception, context=merged_context)
  File "/Users/vineesha/Paysense/arthamatics/venv1/lib/python3.5/site-packages/honeybadger/core.py", line 21, in _send_notice
    payload = create_payload(exception, exc_traceback, request=self.thread_local.request, config=self.config, context=context)
  File "/Users/vineesha/Paysense/arthamatics/venv1/lib/python3.5/site-packages/honeybadger/payload.py", line 138, in create_payload
    'request': request_payload(request, context, config),
  File "/Users/vineesha/Paysense/arthamatics/venv1/lib/python3.5/site-packages/honeybadger/payload.py", line 100, in django_request_payload
    payload['session'] = filter_dict(dict(request.session), config.params_filters)
  File "/Users/vineesha/Paysense/arthamatics/venv1/lib/python3.5/site-packages/honeybadger/utils.py", line 14, in filter_dict
    if data.has_key(key):
AttributeError: 'dict' object has no attribute 'has_key'
```

Since `has_key` is not supported in python 3.

**Comment by vineesha** [comment]
I've raised #18 that fixes this issue specifically. Not sure if there are more wide-ranging changes that need to happen to enable python-3 compatibility.

**Comment by joshuap** [comment]
We are testing under Python-3 (and this is the only issue I'm aware of); if you find any other issues, please report them here and we'll get them fixed. The tests build against 2.7, 3.2 and 3.5: https://travis-ci.org/honeybadger-io/honeybadger-python/builds/166776637

Thanks!

**Comment by joshuap** [comment]
v0.0.3 has been released: https://pypi.python.org/pypi/honeybadger/0.0.3

**Comment by vineesha** [comment]
Great, thanks!
