### ISSUE TITLE
pip install honeybadger fails with ImportError: No module named 'psutil'

### ISSUE THREAD

**Issue by vineesha** [honeybadger-io/honeybadger-python#19]
Is anyone else facing this error?

```
Collecting honeybadger
  Downloading honeybadger-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xn/p6nv0l111q9b_31z501jb46r0000gn/T/pip-build-0l6qr_83/honeybadger/setup.py", line 2, in <module>
        import honeybadger
      File "/private/var/folders/xn/p6nv0l111q9b_31z501jb46r0000gn/T/pip-build-0l6qr_83/honeybadger/honeybadger/__init__.py", line 11, in <module>
        from .core import Honeybadger
      File "/private/var/folders/xn/p6nv0l111q9b_31z501jb46r0000gn/T/pip-build-0l6qr_83/honeybadger/honeybadger/core.py", line 8, in <module>
        from .payload import create_payload
      File "/private/var/folders/xn/p6nv0l111q9b_31z501jb46r0000gn/T/pip-build-0l6qr_83/honeybadger/honeybadger/payload.py", line 11, in <module>
        import psutil
    ImportError: No module named 'psutil'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xn/p6nv0l111q9b_31z501jb46r0000gn/T/pip-build-0l6qr_83/honeybadger/
```

I can resolve it by doing `pip install psutil` before doing `pip install honeybadger`, but I don't want to do that in production. Am I missing something?

**Comment by vineesha** [comment]
From what I can see, `import honeybadger` in setup.py is causing this error. And the import is happening to avoid hardcoding the version. [This](http://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package) has some ideas on how this could be done.

**Comment by joshuap** [comment]
@demsullivan any ideas on this one?
